import { Router, type IRouter } from "express";
import healthRouter from "./health";
import projectsRouter from "./projects";
import filesRouter from "./files";
import aiRouter from "./ai";
import executeRouter from "./execute";
import downloadRouter from "./download";
const router: IRouter = Router();
router.use(healthRouter);
router.use(projectsRouter);
router.use(filesRouter);
router.use(aiRouter);
router.use(executeRouter);
router.use(downloadRouter);
export default router;
